---

- name: 'Run playbook-all_nodes-create_a_vimrc.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-create_a_vimrc.yml

- name: 'Run playbook-all_nodes-install_tmux.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-install_tmux.yml

- name: 'Run playbook-all_nodes-minimal_tmux_configuration.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-minimal_tmux_configuration.yml

- name: 'Run playbook-all_nodes-minimal_bashrc.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-minimal_bashrc.yml

- name: 'Run playbook-all_nodes-geerlingguy.redis.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-geerlingguy.redis.yml

- name: 'Run playbook-all_nodes-linux-system-roles.postgresql.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-linux-system-roles.postgresql.yml

- name: 'Run playbook-all_nodes-configure_postgresql_database_for_netbox.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-configure_postgresql_database_for_netbox.yml

- name: 'Run playbook-all_nodes-jvoss.netbox.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-jvoss.netbox.yml

- name: 'Run playbook-all_nodes-caddy_ansible.caddy_ansible.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-caddy_ansible.caddy_ansible.yml
