---
- name: 'Install netbox'
  hosts: 'all'
  gather_facts: true
  become: true

  pre_tasks:

    - name: Install cronie
      ansible.builtin.package:
        name: cronie
        state: present

    - name: Install acl
      ansible.builtin.package:
        name: acl
        state: present

    - name: Install python3-django
      ansible.builtin.package:
        name: python3-django
        state: present

  roles:
    - role: 'jvoss.netbox'
      netbox_db_username: netbox
      netbox_db_password: anothertotallysecurepassword
      netbox_secret_key: 'andyetanothertotallynotsecurepassword'
      netbox_superusers:
        - username: admin
          password: admin
          email: changeme@example.com
