---
- name: 'Install netbox'
  hosts: 'all'
  gather_facts: true
  become: true

  roles:
    - role: 'jvoss.netbox'
      netbox_db_username: netbox
      netbox_db_password: anothertotallysecurepassword
      netbox_secret_key: 'andyetanothertotallynotsecurepassword'
      netbox_superusers:
        - username: admin
          password: admin
          email: changeme@example.com
