---
- name: 'Install netbox'
  hosts: 'all'
  gather_facts: true
  become: true

  roles:
    - role: 'lae.netbox'
      netbox_stable: true
      netbox_stable_version: 3.4.7
      netbox_install_epel: false
      netbox_superuser_enabled: true
      netbox_superuser_username: admin
      netbox_superuser_password: changeme
      netbox_superuser_email: admin@localhost
      netbox_superuser_create_token: false
      netbox_database: netbox
      netbox_database_user: netbox
      netbox_database_password: totallysecurepassword
      netbox_database_host: localhost
      netbox_database_port: 5432
      redis_bind: 127.0.0.1
